vehicle_rental_system/admin_app/urls.py
from urllib.parse import urlparse
from django.urls import path
from admin_app import views

app_name = 'admin_app'

urlpatterns = [
    path('home/',views.home, name='home'),
    path('addAdmin/',views.addAdmin, name='addAdmin'),
    path('addBooking/',views.addBooking, name='addBooking'),
    path('adminView/',views.adminView, name='adminView'),
    path('bookingReport/',views.bookingReport, name='bookingReport'),
    path('changePassword/',views.changePassword, name='changePassword'),
    path('dashboard/',views.dashboard, name='dashboard'),
    path('requisition/',views.requisition, name='requisition'),
    path('userView/',views.userView, name='userView'),
    path('profile/',views.profile, name='profile'),


]

vehicle_rental_system/login_app/urls.py
from urllib.parse import urlparse
from django.urls import path
from login_app import views

app_name = 'login_app'

urlpatterns = [
    path('home/',views.home, name='home'),
    path('contact/',views.contact, name='contact'),
    path('register/',views.register, name='register'),
    path('user_login/',views.user_login, name='user_login'),
    path('admin_login/',views.admin_login, name='admin_login'),


]

vehicle_rental_system/vehicle_rental_system/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('admin_app/',include('admin_app.urls')),
    path('login_app/',include('login_app.urls')),

]

vehicle_rental_system/admin_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class UserInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username



class addBooking(models.Model):
    vehicle_type_choices =[
        ('car','car'),
        ('micro','micro'),
        ('bike','bike'),
        ('pickup','pickup'),
        ('miniBus','miniBus'),
        ('bus','bus'),
    ]
    vehicleCondition_choices =[
        ('1','1'),
        ('2','2'),
        ('3','3'),
        ('4','4'),
        ('5','5'),
    ]
    type = models.CharField(max_length=10, choices=vehicle_type_choices, default='car')
    vehicleName = models.CharField(max_length=50)
    capacity = models.IntegerField()
    regNum = models.IntegerField()
    cost = models.IntegerField()
    vehicleCondition = models.CharField(max_length=5, choices=vehicleCondition_choices, default='3')
    bookingContact = models.IntegerField()
    description = models.CharField(max_length=500)





vehicle_rental_system/login_app/models.py
from django.db import models

# Create your models here.

vehicle_rental_system/user_app/models.py
from django.db import models

# Create your models here.

vehicle_rental_system/admin_app/forms.py
from dataclasses import field
from django import forms
from django.contrib.auth.models import User
from admin_app.models import UserInfo


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields =('username', 'first_name', 'last_name','email', 'password')

vehicle_rental_system/admin_app/views.py
from django.shortcuts import render
from django.http import HttpResponse
from admin_app.forms import UserForm 
from admin_app.models import addBooking

# Create your views here.

def home(request):
    dict = {}
    return render(request, 'admin_app/index.html', context=dict)

def addAdmin(request):
    registered = False

    if request.method =='POST':
        user_form = UserForm(data=request.POST)
        if user_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            registered = True
    else:
        user_form = UserForm()
    dict = {'user_form': user_form, 'registered':registered}
    return render(request, 'admin_app/add_admin.html', context=dict)

def addBooking(request):

    if request.method =='POST':
        type= request.POST.get('type')
        vehicleName= request.POST.get('vehicleName')
        capacity= request.POST.get('capacity')
        regNum= request.POST.get('regNum')
        cost= request.POST.get('cost')
        vehicleCondition= request.POST.get('vehicleCondition')
        bookingContact= request.POST.get('bookingContact')
        description= request.POST.get('description')

        add_booking = addBooking(type=type, vehicleName=vehicleName, capacity=capacity, regNum=regNum, cost=cost, vehicleCondition=vehicleCondition, bookingContact=bookingContact, description=description)
        add_booking.save()
    dict = {}
    return render(request, 'admin_app/add_booking.html', context=dict)

def adminView(request):
    dict = {}
    return render(request, 'admin_app/admin.html', context=dict)

def bookingReport(request):
    dict = {}
    return render(request, 'admin_app/booking_report.html', context=dict)

def changePassword(request):
    dict = {}
    return render(request, 'admin_app/change_password.html', context=dict)

def dashboard(request):
    dict = {}
    return render(request, 'admin_app/dashboard.html', context=dict)

def requisition(request):
    dict = {}
    return render(request, 'admin_app/requisition.html', context=dict)

def userView(request):
    dict = {}
    return render(request, 'admin_app/user.html', context=dict)

def logout(request):
    dict = {}
    return render(request, 'login_app/home.html', context=dict)

def profile(request):
    dict = {}
    return render(request, 'admin_app/profile.html', context=dict)

vehicle_rental_system/login_app/views.py
from django.shortcuts import render

# Create your views here.

def admin_login(request):
    dict = {}
    return render(request, 'login_app/admin_login.html', context=dict)

def contact(request):
    dict = {}
    return render(request, 'login_app/contact.html', context=dict)

def home(request):
    dict = {}
    return render(request, 'login_app/home.html', context=dict)

def register(request):
    dict = {}
    return render(request, 'login_app/register.html', context=dict)

def user_login(request):
    dict = {}
    return render(request, 'login_app/user_login.html', context=dict)

vehicle_rental_system/user_app/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.

vehicle_rental_system/templates/admin_app/add_admin.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <!-- Popper JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="">
    <title>Add Admin</title>
    <style>
        #navDiv{

            height: 100px; 
            width:auto; 
            background-color:rgb(165, 161, 125);
            padding: 10px;

        }
        a{
            color: black;
        }
        #mainBlock{
            height: 500px;
            width: 500px;
            margin-top: 50px;
            margin-left: 35%;
            padding-top: 15px;
        }
        #heading{
            height: auto;
            width:40%; 
            float: left; 
            color: black;
            padding-top: 2px;
            padding-left: 40px;
            font-size: larger;
        }
        
        .navi{
            padding: 15px;
            background-color: lightgray;
            color: black;
        }
        span{
            
            margin-top: 10px;
            color: black;
        }
        
    </style>
    
</head>
<body>

    <div id="navDiv">
        <span id="heading">
            <h1>Vehicle Rental System</h1>
        </span>
        <div style="margin-top: 25px;">
            <a href="{% url 'admin_app:dashboard' %}"><span class="navi">Dashboard</span></a>
            <a href="{% url 'admin_app:bookingReport' %}"><span class="navi">Booking Report</span></a>
            <a href="{% url 'admin_app:requisition' %}"><span class="navi">Requsition</span></a>
            <a href="{% url 'admin_app:userView' %}"><span class="navi">User</span></a>
            <a href="{% url 'admin_app:adminView' %}"><span class="navi">Admin</span></a>
            <a href="{% url 'login_app:home' %}"><span class="navi">Logout</span></a>

        </div> 
        

    </div>
    
    <div id="mainBlock" class="container">
        {% if registered %}
        <div class="alert alert-success">
            Registration Successful!!....
        </div>

        {% else %}
        <hr>
        <h1>Add Admin</h1>
        <hr>
        <form enctype="multipart/form-data" action="" method="POST" >
            {{ user_form.as_p }}
            {% csrf_token %}
            <br>
            <input style="height:auto;width:100px; margin-left: 180px;" type="submit" name="submit" value="Register">
        
        </form>
        {% endif %}
    </div>

    
    
</body>
</html>

vehicle_rental_system/templates/admin_app/add_booking.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <!-- Popper JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="">
    <title>Add Booking</title>
    <style>
        #navDiv{

            height: 100px; 
            width:auto; 
            background-color:rgb(165, 161, 125);
            padding: 10px;
            position: relative;

        }
        #mainBlock{
            height: 500px;
            width: 500px;
            margin-top: 25px;
            margin-left: 35%;
            padding-top: 15px;
        }
        #heading{
            height: auto;
            width:40%; 
            float: left; 
            color: black;
            padding-top: 2px;
            padding-left: 40px;
            font-size: larger;
        }
        
        .navi{
            padding: 15px;
            background-color: lightgray;
            color: black;
        }
        span{
            
            margin-top: 10px;
            color: black;
        }
        .radio{
            padding-left: 3px;
            padding-right: 8px;
        }
        a{
            color: black;
        }
        
    </style>
    
</head>
<body>

    <div id="navDiv">
        <span id="heading">
            <h1>Vehicle Rental System</h1>
        </span>
        <div style="margin-top: 25px;">
            <a href="{% url 'admin_app:dashboard' %}"><span class="navi">Dashboard</span></a>
            <a href="{% url 'admin_app:bookingReport' %}"><span class="navi">Booking Report</span></a>
            <a href="{% url 'admin_app:requisition' %}"><span class="navi">Requsition</span></a>
            <a href="{% url 'admin_app:userView' %}"><span class="navi">User</span></a>
            <a href="{% url 'admin_app:adminView' %}"><span class="navi">Admin</span></a>
            <a href="{% url 'login_app:home' %}"><span class="navi">Logout</span></a>

        </div> 
        

    </div>
    
    <div id="mainBlock">
        <hr>
        <h1>Add Booking</h1>
        <hr>
        <form method="POST" action="{% url 'addBooking' %}">
            
            <label for="type">Vehicle Type:</label>
            <select name="type" id="vehicleType" style="width: 100px">
                <option selected="selected" disabled>--Select--</option>
                <option name="type" value="car">Car</option>
                <option name="type" value="micro">MicroBus</option>
                <option name="type" value="bike">Bike</option>
                <option name="type" value="pickup">Pickup</option>
                <option name="type" value="miniBus">Mini Bus</option>
                <option name="type" value="bus">Bus</option>
            </select>
            <br><br>
            <label for="vehicleName">Name</label>
            <input class="form-control" type="text" name="vehicleName" placeholder="Vehicle Name..." required>
            <br>
            <label for="capacity">Capacity</label>
            <input class="form-control" type="number" name="capacity" placeholder="How many passenger..." required>
            <br>
            <label for="regNum">Vehicle Registration Number</label>
            <input class="form-control" type="number" name="regNum" placeholder="Enter vehicle number..." required>
            <br>
            <label for="cost">Cost</label>
            <input class="form-control" type="number" name="cost" placeholder="Cost per day..." required>
            <br>
            <label style="padding-right: 20px;" for="vehicleCondition">Vehicle Condition: </label><br>
            <input class="radio" type="radio" id="" name="vehicleCondition" value="1"><label class="radio"for="vehicleCondition">Very Bad</label>
            <input class="radio" type="radio" id="" name="vehicleCondition" value="2"><label class="radio"for="vehicleCondition">Bad</label>
            <input class="radio" type="radio" id="" name="vehicleCondition" value="3"><label class="radio"for="vehicleCondition">Normal</label>
            <input class="radio" type="radio" id="" name="vehicleCondition" value="4"><label class="radio"for="vehicleCondition">Good</label>
            <input class="radio" type="radio" id="" name="vehicleCondition" value="5"><label class="radio"for="vehicleCondition">Very Good</label>
            <br><br>
            <label for="bookingContact">Booking Contact</label>
            <input class="form-control" type="number" name="bookingContact" placeholder="Booking Contact..." required>
            <br>
            <label for="description">Description</label>
            <textarea class="form-control" name="description" id="" cols="65" rows="6" placeholder="Vehicle full description.."></textarea>
            <br>
            {% csrf_token %}
            <br>
            <input style="height:40px;width:120px; margin-left: 180px; background-color: darkgray;" type="submit" name="add" value="Add">
            <br><br>
        </form>
    </div>

    
    
</body>
</html>

vehicle_rental_system/templates/admin_app/admin.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <!-- Popper JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="">
    <title>Admin</title>
    <style>
        #navDiv{

            height: 100px; 
            width:auto; 
            background-color:rgb(165, 161, 125);
            padding: 10px;

        }
        
        #heading{
            height: auto;
            width:40%; 
            float: left; 
            color: black;
            padding-top: 2px;
            padding-left: 40px;
            font-size: larger;
        }
        #mainBlock{
            height: 500px;
            width: 500px;
            margin-top: 50px;
            margin-left: 35%;
            padding-top: 15px;
        }
        .navi{
            padding: 15px;
            background-color: lightgray;
            color: black;
        }
        span{
            
            margin-top: 10px;
            color: black;
        }
        a{
            color: black;
        }
    </style>
    
</head>
<body>

    <div id="navDiv">
        <span id="heading">
            <h1>Vehicle Rental System</h1>
        </span>
        <div style="margin-top: 25px;">
            <a href="{% url 'admin_app:dashboard' %}"><span class="navi">Dashboard</span></a>
            <a href="{% url 'admin_app:bookingReport' %}"><span class="navi">Booking Report</span></a>
            <a href="{% url 'admin_app:requisition' %}"><span class="navi">Requsition</span></a>
            <a href="{% url 'admin_app:userView' %}"><span class="navi">User</span></a>
            <a href="{% url 'admin_app:adminView' %}"><span class="navi">Admin</span></a>
            <a href="{% url 'login_app:home' %}"><span class="navi">Logout</span></a>

        </div>
        

    </div>
    
    <div id="mainBlock">
        <h1>Admin</h1>
    </div>

    
    
</body>
</html>

vehicle_rental_system/templates/admin_app/booking_report.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <!-- Popper JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="">
    <title>Booking Report</title>
    <style>
        #navDiv{

            height: 100px; 
            width:auto; 
            background-color:rgb(165, 161, 125);
            padding: 10px;

        }
        
        #heading{
            height: auto;
            width:40%; 
            float: left; 
            color: black;
            padding-top: 2px;
            padding-left: 40px;
            font-size: larger;
        }
        #mainBlock{
            height: 500px;
            width: 500px;
            margin-top: 50px;
            margin-left: 35%;
            padding-top: 15px;
        }
        .navi{
            padding: 15px;
            background-color: lightgray;
            color: black;
        }
        span{
            
            margin-top: 10px;
            color: black;
        }
        a{
            color: black;
        }
    </style>
    
</head>
<body>

    <div id="navDiv">
        <span id="heading">
            <h1>Vehicle Rental System</h1>
        </span>
        <div style="margin-top: 25px;">
            <a href="{% url 'admin_app:dashboard' %}"><span class="navi">Dashboard</span></a>
            <a href="{% url 'admin_app:bookingReport' %}"><span class="navi">Booking Report</span></a>
            <a href="{% url 'admin_app:requisition' %}"><span class="navi">Requsition</span></a>
            <a href="{% url 'admin_app:userView' %}"><span class="navi">User</span></a>
            <a href="{% url 'admin_app:adminView' %}"><span class="navi">Admin</span></a>
            <a href="{% url 'login_app:home' %}"><span class="navi">Logout</span></a>

        </div>
        

    </div>
    
    <div id="mainBlock">
        <h1>Booking Report</h1>
    </div>

    
    
</body>
</html>

vehicle_rental_system/templates/admin_app/change_password.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <!-- Popper JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="">
    <title>Change Password</title>
    <style>
        #navDiv{

            height: 100px; 
            width:auto; 
            background-color:rgb(165, 161, 125);
            padding: 10px;

        }
        
        #heading{
            height: auto;
            width:40%; 
            float: left; 
            color: black;
            padding-top: 2px;
            padding-left: 40px;
            font-size: larger;
        }
        #mainBlock{
            height: 500px;
            width: 500px;
            margin-top: 50px;
            margin-left: 35%;
            padding-top: 15px;
        }
        .navi{
            padding: 15px;
            background-color: lightgray;
            color: black;
        }
        span{
            
            margin-top: 10px;
            color: black;
        }
        a{
            color: black;
        }
    </style>
    
</head>
<body>

    <div id="navDiv">
        <span id="heading">
            <h1>Vehicle Rental System</h1>
        </span>
        <div style="margin-top: 25px;">
            <a href="{% url 'admin_app:dashboard' %}"><span class="navi">Dashboard</span></a>
            <a href="{% url 'admin_app:bookingReport' %}"><span class="navi">Booking Report</span></a>
            <a href="{% url 'admin_app:requisition' %}"><span class="navi">Requsition</span></a>
            <a href="{% url 'admin_app:userView' %}"><span class="navi">User</span></a>
            <a href="{% url 'admin_app:adminView' %}"><span class="navi">Admin</span></a>
            <a href="{% url 'login_app:home' %}"><span class="navi">Logout</span></a>

        </div>
        

    </div>
    
    <div id="mainBlock">
        <hr>
        <h1>Change Password</h1>
        <hr>
        <form method="POST" action="">
            
            <input class="form-control" type="password" name="password" placeholder="Old password" required>
            <br>
            <input class="form-control" type="password" name="newPassword1" placeholder="New password" required>
            <br>
            <input class="form-control" type="password" name="newPassword2" placeholder="Repeat new password" required>
            <br>
            <br>
            {% csrf_token %}
            <br>
            <input style="height:auto;width:100px; margin-left: 180px;" type="submit" name="register" value="Register">
        
        </form>
    </div>

    
    
</body>
</html>

vehicle_rental_system/templates/admin_app/dashboard.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <!-- Popper JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="">
    <title>Dashboard</title>
    <style>
        #navDiv{

            height: 100px; 
            width:auto; 
            background-color:rgb(165, 161, 125);
            padding: 10px;

        }
        
        #heading{
            height: auto;
            width:40%; 
            float: left; 
            color: black;
            padding-top: 2px;
            padding-left: 40px;
            font-size: larger;
        }
        
        .navi{
            padding: 15px;
            background-color: lightgray;
            color: black;
        }
        span{
            
            margin-top: 10px;
            color: black;
        }
        #mainBlock{
            height: 500px;
            width: 500px;
            margin-top: 50px;
            margin-left: 35%;
            padding-top: 15px;
        }
        .button{
            height: 10%;
            width: 90%;
            background-color: darkgray;
            text-align: left;
            padding-top: 2%;
            padding-left: 15px;
            margin-top: 5px;


        }
        p{
            color: black;
        }
        a{
            color: black;
        }
    </style>
    
</head>
<body>

    <div id="navDiv">
        <span id="heading">
            <h1>Vehicle Rental System</h1>
        </span>
        <div style="margin-top: 25px;">
            <a href="{% url 'admin_app:dashboard' %}"><span class="navi">Dashboard</span></a>
            <a href="{% url 'admin_app:bookingReport' %}"><span class="navi">Booking Report</span></a>
            <a href="{% url 'admin_app:requisition' %}"><span class="navi">Requsition</span></a>
            <a href="{% url 'admin_app:userView' %}"><span class="navi">User</span></a>
            <a href="{% url 'admin_app:adminView' %}"><span class="navi">Admin</span></a>
            <a href="{% url 'login_app:home' %}"><span class="navi">Logout</span></a>

        </div> 
        

    </div>
    
    <div id="mainBlock">
        <hr>
        <h1>Dashboard</h1>
        <hr>

        <a href="{% url 'admin_app:addAdmin' %}"><p class="button"><b>Add Admin</b></p></a>
        <a href="{% url 'admin_app:addBooking' %}"><p class="button"><b>Add Booking</b></p></a>
        <a href="{% url 'admin_app:profile' %}"><p class="button"><b>Profile</b></p></a>
        <a href="{% url 'admin_app:changePassword' %}"><p class="button"><b>Change Password</b></p></a>


    </div>

    
    
</body>
</html>

vehicle_rental_system/templates/admin_app/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <!-- Popper JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="">
    <title>Home</title>
    <style>
        #navDiv{

            height: 100px; 
            width:auto; 
            background-color:rgb(165, 161, 125);
            padding: 10px;

        }
        
        #heading{
            height: auto;
            width:40%; 
            float: left; 
            color: black;
            padding-top: 2px;
            padding-left: 40px;
            font-size: larger;
        }
        #mainBlock{
            height: 500px;
            width: 500px;
            margin-top: 50px;
            margin-left: 35%;
            padding-top: 15px;
        }
        .navi{
            padding: 15px;
            background-color: lightgray;
            color: black;
        }
        span{
            
            margin-top: 10px;
            color: black;
        }
        a{
            color: black;
        }
    </style>
    
</head>
<body>

    <div id="navDiv">
        <span id="heading">
            <h1>Vehicle Rental System</h1>
        </span>
        <div style="margin-top: 25px;">
            <a href="{% url 'admin_app:dashboard' %}"><span class="navi">Dashboard</span></a>
            <a href="{% url 'admin_app:bookingReport' %}"><span class="navi">Booking Report</span></a>
            <a href="{% url 'admin_app:requisition' %}"><span class="navi">Requsition</span></a>
            <a href="{% url 'admin_app:userView' %}"><span class="navi">User</span></a>
            <a href="{% url 'admin_app:adminView' %}"><span class="navi">Admin</span></a>
            <a href="{% url 'login_app:home' %}"><span class="navi">Logout</span></a>

        </div>
        

    </div>
    
    <div id="mainBlock">
        <h1>home</h1>
    </div>

    
    
</body>
</html>